---
title: "DataScience_hm5"
author: "KaiYu He(kh3074)"
date: "11/16/2021"
output: html_document
---
```{r}
library(tidyverse)
```

# Problem 1  
```{r}
homicide_df = 
  read_csv("data/homicide-data.csv",na = c("","Unkonw")) %>%
  mutate(
    city_state = str_c(city,",",state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>%
  relocate(city_state)%>%
  filter(city_state != "Tusla,AL")
homicide_df%>%count(city_state)
```

Let's focus on Baltimore,MD.
```{r}
baltimore_df = 
  homicide_df%>%
  filter(city_state == "Baltimore,MD")

baltimore_summary = 
  baltimore_df%>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
  x = baltimore_summary%>%pull(unsolved),
  n = baltimore_summary%>%pull(n)
  )

baltimore_test %>%
  broom::tidy()
```

let's try to iterate across cities!
First off, write a function.
```{r}
prop_test_function = function(city_df)
  {
  city_summary = 
  city_df%>%
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

city_test = 
  prop.test(
  x = city_summary%>%pull(unsolved),
  n = city_summary%>%pull(n)
  )
  }
```

Now, let's iterate across all cities.
```{r}
results_df =
  homicide_df%>%
  nest(data = uid:resolution)%>%
  mutate(
    test_result = map(data,prop_test_function),
    tidy_result = map(test_result,broom::tidy)
  )%>%
  select(city_state,tidy_result)%>%
  unnest(tidy_result)%>%
  select(city_state,estimate,starts_with("conf"))
results_df

```

Try to make a plot showing estimates and confidence intervals.

```{r}
results_df%>%
  filter(city_state!="Tulsa,AL")%>%
  mutate(city_state = fct_reorder(city_state,estimate))%>%
  ggplot(aes(x = city_state,y = estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low,ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90,vjust = 0.5,hjust = 1))
```



# Problem 2









